// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAqT_r9fZG2AWAOQdT65ZLLfPwIM0QP08',
    appId: '1:748305256581:web:069deef70ce41326dfd9ec',
    messagingSenderId: '748305256581',
    projectId: 'vintaide',
    authDomain: 'vintaide.firebaseapp.com',
    storageBucket: 'vintaide.firebasestorage.app',
    measurementId: 'G-SCHXDELGH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZzQfFJG6tr3gxYtQEXVEMg6-pZpp0Kk',
    appId: '1:748305256581:android:0bf7eb558206af0ddfd9ec',
    messagingSenderId: '748305256581',
    projectId: 'vintaide',
    storageBucket: 'vintaide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzwflcg1v-Mi4dcAzb0AjFw4RFxWzzRIg',
    appId: '1:748305256581:ios:8261dd7ac7c97236dfd9ec',
    messagingSenderId: '748305256581',
    projectId: 'vintaide',
    storageBucket: 'vintaide.firebasestorage.app',
    iosBundleId: 'com.example.vintaide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzwflcg1v-Mi4dcAzb0AjFw4RFxWzzRIg',
    appId: '1:748305256581:ios:8261dd7ac7c97236dfd9ec',
    messagingSenderId: '748305256581',
    projectId: 'vintaide',
    storageBucket: 'vintaide.firebasestorage.app',
    iosBundleId: 'com.example.vintaide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAqT_r9fZG2AWAOQdT65ZLLfPwIM0QP08',
    appId: '1:748305256581:web:d76d06566076a491dfd9ec',
    messagingSenderId: '748305256581',
    projectId: 'vintaide',
    authDomain: 'vintaide.firebaseapp.com',
    storageBucket: 'vintaide.firebasestorage.app',
    measurementId: 'G-FWBFPY755Y',
  );
}
